### ISSUE TITLE
Compile Problem 

### ISSUE THREAD

**Issue by Chenfeng1271** [RyanHangZhou/tensorflow-LG-GAN#3]
Thanks for your excellent work and code. I meet some problems when compiling the TF operators.  I can well compile 3d_interpolate and interpolate file, but the other files fail. I use CUDA10.0 Tensorflow 1.14.0.  I know three of operators are from PointNet++. Could you tell me where the nn_distance, approxmatch from?

**Comment by RyanHangZhou** [comment]
You can find them in the code of PU-Net. They are measurements of distance evaluations between two point cloud sets. Check more on GitHub society.

**Comment by RyanHangZhou** [comment]
> Thanks for your excellent work and code. I meet some problems when compiling the TF operators. I can well compile 3d_interpolate and interpolate file, but the other files fail. I use CUDA10.0 Tensorflow 1.14.0. I know three of operators are from PointNet++. Could you tell me where the nn_distance, approxmatch from?

You can find them in the code of PU-Net. They are measurements of distance evaluations between two point cloud sets. Check more on GitHub society.

**Comment by Chenfeng1271** [comment]
Thanks for your reply. I want to download the pretrained PointNet model from [GoogleDive](https://drive.google.com/drive/folders/11c6v_umZmSHiq-1TLKpSyPQK0E9fDkMU) you provided, but it seems to need your access permision.

**Comment by RyanHangZhou** [comment]
> Thanks for your reply. I want to download the pretrained PointNet model from [GoogleDive](https://drive.google.com/drive/folders/11c6v_umZmSHiq-1TLKpSyPQK0E9fDkMU) you provided, but it seems to need your access permision.

Sure, now you can download it. Please check it.
